-- Seed Teams
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (2, 'South Africa', 'https://flagcdn.com/w80/za.png', 'RSA', 'A');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (9, 'Brazil', 'https://flagcdn.com/w80/br.png', 'BRA', 'C');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (12, 'Scotland', 'https://flagcdn.com/w80/gb-sct.png', 'SCO', 'C');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (16, 'Turkey', 'https://flagcdn.com/w80/tr.png', 'TUR', 'D');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (19, 'Ivory Coast', 'https://flagcdn.com/w80/ci.png', 'CIV', 'E');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (21, 'Netherlands', 'https://flagcdn.com/w80/nl.png', 'NED', 'F');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (30, 'Cape Verde', 'https://flagcdn.com/w80/cv.png', 'CPV', 'H');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (33, 'France', 'https://flagcdn.com/w80/fr.png', 'FRA', 'I');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (24, 'Tunisia', 'https://flagcdn.com/w80/tn.png', 'TUN', 'F');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (26, 'Egypt', 'https://flagcdn.com/w80/eg.png', 'EGY', 'G');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (35, 'Iraq', 'https://flagcdn.com/w80/iq.png', 'IRQ', 'I');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (41, 'Portugal', 'https://flagcdn.com/w80/pt.png', 'POR', 'K');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (43, 'Uzbekistan', 'https://flagcdn.com/w80/uz.png', 'UZB', 'K');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (44, 'Colombia', 'https://flagcdn.com/w80/co.png', 'COL', 'K');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (20, 'Ecuador', 'https://flagcdn.com/w80/ec.png', 'ECU', 'E');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (22, 'Japan', 'https://flagcdn.com/w80/jp.png', 'JPN', 'F');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (28, 'New Zealand', 'https://flagcdn.com/w80/nz.png', 'NZL', 'G');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (31, 'Saudi Arabia', 'https://flagcdn.com/w80/sa.png', 'KSA', 'H');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (39, 'Austria', 'https://flagcdn.com/w80/at.png', 'AUT', 'J');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (47, 'Ghana', 'https://flagcdn.com/w80/gh.png', 'GHA', 'L');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (3, 'South Korea', 'https://flagcdn.com/w80/kr.png', 'KOR', 'A');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (29, 'Spain', 'https://flagcdn.com/w80/es.png', 'ESP', 'H');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (36, 'Norway', 'https://flagcdn.com/w80/no.png', 'NOR', 'I');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (37, 'Argentina', 'https://flagcdn.com/w80/ar.png', 'ARG', 'J');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (42, 'Democratic Republic of the Congo', 'https://flagcdn.com/w80/cd.png', 'COD', 'K');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (45, 'England', 'https://flagcdn.com/w80/gb-eng.png', 'ENG', 'L');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (4, 'Czech Republic', 'https://flagcdn.com/w80/cz.png', 'CZE', 'A');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (5, 'Canada', 'https://flagcdn.com/w80/ca.png', 'CAN', 'B');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (7, 'Qatar', 'https://flagcdn.com/w80/qa.png', 'QAT', 'B');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (8, 'Switzerland', 'https://flagcdn.com/w80/ch.png', 'SUI', 'B');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (10, 'Morocco', 'https://flagcdn.com/w80/ma.png', 'MAR', 'C');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (14, 'Paraguay', 'https://flagcdn.com/w80/py.png', 'PAR', 'D');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (18, 'Curaçao', 'https://flagcdn.com/w80/cw.png', 'CUW', 'E');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (23, 'Sweden', 'https://flagcdn.com/w80/se.png', 'SWE', 'F');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (38, 'Algeria', 'https://flagcdn.com/w80/dz.png', 'ALG', 'J');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (40, 'Jordan', 'https://flagcdn.com/w80/jo.png', 'JOR', 'J');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (11, 'Haiti', 'https://flagcdn.com/w80/ht.png', 'HAI', 'C');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (17, 'Germany', 'https://flagcdn.com/w80/de.png', 'GER', 'E');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (32, 'Uruguay', 'https://flagcdn.com/w80/uy.png', 'URU', 'H');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (34, 'Senegal', 'https://flagcdn.com/w80/sn.png', 'SEN', 'I');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (48, 'Panama', 'https://flagcdn.com/w80/pa.png', 'PAN', 'L');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (1, 'Mexico', 'https://flagcdn.com/w80/mx.png', 'MEX', 'A');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (6, 'Bosnia and Herzegovina', 'https://flagcdn.com/w80/ba.png', 'BIH', 'B');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (13, 'United States', 'https://flagcdn.com/w80/us.png', 'USA', 'D');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (15, 'Australia', 'https://flagcdn.com/w80/au.png', 'AUS', 'D');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (25, 'Belgium', 'https://flagcdn.com/w80/be.png', 'BEL', 'G');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (27, 'Iran', 'https://flagcdn.com/w80/ir.png', 'IRN', 'G');
INSERT OR REPLACE INTO teams (id, name_en, flag, fifa_code, group_name) VALUES (46, 'Croatia', 'https://flagcdn.com/w80/hr.png', 'CRO', 'L');
